[package]
name = "comp_input"
version = "0.1.0"
authors = ["Matteo Signer <matteo.signer@gmail.com>"]
description = "Input library for competitive programming"
license = "MIT/Apache-2.0"

[dependencies]
